version: '3.6'
#version: '3.7' - need downgrade due to external machine config


services:

  backend:
    container_name: "backend"
    build:
      context: ./services/backend
      dockerfile: Dockerfile-dev
    volumes:
      - './services/backend:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=developmentdocker-compose
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://admin:admin@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://admin:admin@users-db:5432/users_test
      - SECRET_KEY=my_secret_key
    depends_on:
      - users-db
      - mongo-db

  users-db:
    container_name: "users-database"
    build:
      context: ./services/backend/project/db_postgresql
      dockerfile: Dockerfile
    ports:
      - 5346:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  mongo-db:
    container_name: "crawler-database"
    image: mongo:3.6-xenial
    volumes:
      - './services/backend/data:/usr/src/app/'
    command: mongod

  nginx:
    container_name: "nginx"
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - backend

#  swagger:
#    container_name: "swagger"
#    build:
#      context: ./services/swagger
#      dockerfile: Dockerfile-dev
#    ports:
#      - 3008:8080
#    volumes:
#      - ./services/swagger/swagger.json:/swagger.json
#    environment:
#      - SWAGGER_JSON=/swagger.json
#      - BASE_URL=/swagger
#    depends_on:
#      - backend

  swagger-editor:
    container_name: "swagger-editor"
    image: swaggerapi/swagger-editor
    ports:
      - 8082:8080

  swagger-ui:
    container_name: "swagger-ui"
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    volumes:
      - ./services/swagger/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json
      # API_URL: ""
    depends_on:
      - backend

#  swagger-api:
#    container_name: "swagger-api"
#    image: danielgtaylor/apisprout
#    ports:
#      - 8083:8000q
#    volumes:
#      - ./services/swagger/swagger.json:/swagger.json
#    command: /swagger.json
#    depends_on:
#      - backend
