version: '3.6'
#version: '3.7' - need downgrade due to external machine config


services:

  backend:
    container_name: "backend"
    build:
      context: ./services/backend
      dockerfile: Dockerfile-dev
    volumes:
      - './services/backend:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=developmentdocker-compose
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://admin:admin@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://admin:admin@users-db:5432/users_test
      - SECRET_KEY=my_secret_key
    depends_on:
      - users-db
      - mongo-db

  celery:
    container_name: "celery"
    build:
      context: ./services/backend
      dockerfile: Dockerfile-dev
    entrypoint: celery worker -A project.worker.worker:celery --loglevel=INFO
    environment:
      CELERY_BACKEND: 'redis://localhost:6379/0'
      CELERY_BROKER: 'redis://localhost:6379/0'
    depends_on:
      - redis

  redis:
    container_name: "redis"
    image: redis:3.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - './services/backend/data:/usr/src/app/redis/'
    entrypoint: redis-server --appendonly yes
    restart: always

  users-db:
    container_name: "users-database"
    build:
      context: ./services/backend/project/db_postgresql
      dockerfile: Dockerfile
    ports:
      - 5346:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  mongo-db:
    container_name: "crawler-database"
    image: mongo:3.6-xenial
    volumes:
      - './services/backend/data:/usr/src/app/'
    command: mongod

  nginx:
    container_name: "nginx"
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - backend

  swagger-editor:
    container_name: "swagger-editor"
    image: swaggerapi/swagger-editor
    ports:
      - 8082:8080

  swagger-ui:
    container_name: "swagger-ui"
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    volumes:
      - ./services/swagger/swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json
      # API_URL: ""
    depends_on:
      - backend
