FROM python:3.7.2-slim

RUN apt-get update && \
   apt-get -y install netcat && \
   apt-get -y install --no-install-recommends apt-utils && \
   apt-get clean

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

COPY . /usr/src/app

RUN [ "chmod",  "+x", "/usr/src/app/entrypoint.sh" ]

CMD [ "/usr/src/app/entrypoint.sh" ]