FROM python:3.7.2-slim

RUN apt-get update && \
   apt-get -y install netcat && \
   apt-get -y install --no-install-recommends apt-utils && \
   apt-get clean

COPY . /app

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /app/entrypoint.sh

RUN [ "chmod",  "+x", "/app/entrypoint.sh" ]

CMD [ "/app/entrypoint.sh" ]