FROM python:3.7.2-slim

RUN apt-get update && \
   apt-get -y install netcat && \
   apt-get clean

#RUN apk update
#RUN apk add --virtual build-deps gcc python-dev musl-dev
#RUN apk add postgresql-dev
#RUN apk add netcat-openbsh

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

COPY . /usr/src/app

RUN [ "chmod",  "+x", "/usr/src/app/entrypoint.sh" ]

CMD [ "/usr/src/app/entrypoint.sh" ]